// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO4hOt_JX3lkkic4-vZtlpRbOvex0RkxA',
    appId: '1:956241077905:web:902ca32a9d63e694384130',
    messagingSenderId: '956241077905',
    projectId: 'worthitapp-52fc7',
    authDomain: 'worthitapp-52fc7.firebaseapp.com',
    storageBucket: 'worthitapp-52fc7.firebasestorage.app',
    measurementId: 'G-69SC4F8RP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTbiuorSLiEh-U2LvvqXB1Syiae_K2zlI',
    appId: '1:956241077905:android:0b800cce25ecac73384130',
    messagingSenderId: '956241077905',
    projectId: 'worthitapp-52fc7',
    storageBucket: 'worthitapp-52fc7.firebasestorage.app',
  );
}
